/**
 * Dummy Subcategories Data
 * Subcategories will be mapped to category IDs after categories are inserted
 */

export const dummySubcategories = [
  // Electronics subcategories (categoryId will be 1)
  {
    categoryIndex: 0, // Maps to Electronics
    name: 'Smartphones',
    slug: 'smartphones',
    description: 'Latest smartphones and mobile devices',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400',
    displayOrder: 1,
    active: true,
    featured: true,
  },
  {
    categoryIndex: 0,
    name: 'Laptops',
    slug: 'laptops',
    description: 'Laptops and notebooks for work and gaming',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400',
    displayOrder: 2,
    active: true,
    featured: true,
  },
  {
    categoryIndex: 0,
    name: 'Headphones',
    slug: 'headphones',
    description: 'Wireless and wired headphones',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
    displayOrder: 3,
    active: true,
    featured: false,
  },
  {
    categoryIndex: 0,
    name: 'Cameras',
    slug: 'cameras',
    description: 'Digital cameras and accessories',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400',
    displayOrder: 4,
    active: true,
    featured: false,
  },

  // Fashion subcategories (categoryId will be 2)
  {
    categoryIndex: 1,
    name: "Men's Clothing",
    slug: 'mens-clothing',
    description: 'Shirts, pants, and formal wear for men',
    image: 'https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?w=400',
    displayOrder: 1,
    active: true,
    featured: true,
  },
  {
    categoryIndex: 1,
    name: "Women's Clothing",
    slug: 'womens-clothing',
    description: 'Dresses, tops, and ethnic wear for women',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400',
    displayOrder: 2,
    active: true,
    featured: true,
  },
  {
    categoryIndex: 1,
    name: 'Footwear',
    slug: 'footwear',
    description: 'Shoes, sandals, and sneakers',
    image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400',
    displayOrder: 3,
    active: true,
    featured: false,
  },
  {
    categoryIndex: 1,
    name: 'Accessories',
    slug: 'accessories',
    description: 'Bags, watches, and jewelry',
    image: 'https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?w=400',
    displayOrder: 4,
    active: true,
    featured: false,
  },

  // Home & Kitchen subcategories (categoryId will be 3)
  {
    categoryIndex: 2,
    name: 'Furniture',
    slug: 'furniture',
    description: 'Sofas, beds, and tables',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400',
    displayOrder: 1,
    active: true,
    featured: true,
  },
  {
    categoryIndex: 2,
    name: 'Kitchen Appliances',
    slug: 'kitchen-appliances',
    description: 'Mixers, blenders, and cookware',
    image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400',
    displayOrder: 2,
    active: true,
    featured: false,
  },
  {
    categoryIndex: 2,
    name: 'Home Decor',
    slug: 'home-decor',
    description: 'Wall art, lamps, and decorative items',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400',
    displayOrder: 3,
    active: true,
    featured: false,
  },

  // Books subcategories (categoryId will be 4)
  {
    categoryIndex: 3,
    name: 'Fiction',
    slug: 'fiction',
    description: 'Novels and story books',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    displayOrder: 1,
    active: true,
    featured: true,
  },
  {
    categoryIndex: 3,
    name: 'Non-Fiction',
    slug: 'non-fiction',
    description: 'Biography, history, and educational books',
    image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400',
    displayOrder: 2,
    active: true,
    featured: false,
  },
  {
    categoryIndex: 3,
    name: "Children's Books",
    slug: 'childrens-books',
    description: 'Story books and learning materials for kids',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400',
    displayOrder: 3,
    active: true,
    featured: false,
  },

  // Sports & Fitness subcategories (categoryId will be 5)
  {
    categoryIndex: 4,
    name: 'Gym Equipment',
    slug: 'gym-equipment',
    description: 'Dumbbells, treadmills, and exercise machines',
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400',
    displayOrder: 1,
    active: true,
    featured: true,
  },
  {
    categoryIndex: 4,
    name: 'Outdoor Sports',
    slug: 'outdoor-sports',
    description: 'Cricket, football, and outdoor games',
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400',
    displayOrder: 2,
    active: true,
    featured: false,
  },
  {
    categoryIndex: 4,
    name: 'Yoga & Fitness',
    slug: 'yoga-fitness',
    description: 'Yoga mats, resistance bands, and fitness accessories',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    displayOrder: 3,
    active: true,
    featured: false,
  },
];
